config/routes.rb
Dom3::Application.routes.draw do
  resources :players do
    member do
      put 'updateAdmin'
    end
  end

  resources :signups

  resources :games

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "createuser" => "users#new", :as => "createuser"
  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :password_resets
  root :to => "home#index"

end

app/models/signup.rb
class Signup < ActiveRecord::Base
  attr_accessible :game_id, :nation_id, :password, :status, :player_id, :status_cd, :turn, :turn_cd, :username
  as_enum :status, :Alive => 0, :AI => 1, :Defeated => 3, :Defeated_This_Turn => 4
  as_enum :turn, :Outstanding => 0, :Partial => 1, :Submitted => 2
  validates_presence_of :game_id
  validates_presence_of :nation_id
  validates_presence_of :player_id
  belongs_to :game
  belongs_to :player
  validates :nation_id, :uniqueness => {:scope => :game_id,
                                        :message => "each nation can only have 1 signup per game"}

  validates :game_id, :numericality => { :only_integer => true}
  validates :nation_id, :numericality => { :only_integer => true, :greater_than => -1, :less_than => 201 }
  validates :player_id, :numericality => { :only_integer => true, :greater_than => -1 }
  validates :password, :presence => true, :if => :passwordRequired?
  after_create :init

  def init
    self.status = :Alive
    self.turn = :Outstanding
  end

  def passwordRequired?
    self.game.requires_passwords
  end

  def username
    if self.player.nil?
      return ''
    else
      return self.player.user.username
    end

  end

  def username=(name)
    user = User.find_by_username(name)
    if !user.nil?
      self.player_id = user.player.id
    end
  end
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  # GET /signups
  # GET /signups.json
  before_filter :require_login, :only => [:create, :destroy]
  before_filter :signup_owner, :only => [:destroy]
=begin
  def index
    @signups = Signup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @signups }
    end
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
    @signup = Signup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @signup }
    end
  end

  # GET /signups/new
  # GET /signups/new.json
  def new
    @signup = Signup.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @signup }
    end
  end

  # GET /signups/1/edit
  def edit
    @signup = Signup.find(params[:id])
  end
=end
  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(params[:signup])

    respond_to do |format|
      if @signup.save
        flash[:notice] = 'Signup was successfully created.'
        format.html { redirect_to :controller => "games", :action => "show", :id => @signup.game_id }
        format.json { render json: @signup, status: :created, location: @signup }
      else
        flash[:notice] = 'Error creating signup.'
        format.html { redirect_to :controller => "games", :action => "show", :id => @signup.game_id }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end
=begin
  # PUT /signups/1
  # PUT /signups/1.json
  def update
    @signup = Signup.find(params[:id])

    respond_to do |format|
      if @signup.update_attributes(params[:signup])
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end
=end
  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup = Signup.find(params[:id])
    @game_id = @signup.game_id
    @signup.destroy

    respond_to do |format|
      flash[:notice] = 'Signup deleted'
      format.html { redirect_to :controller => "games", :action => "show", :id => @game_id}
      format.json { head :no_content }
    end
  end
  def signup_owner()
    @signup = Signup.find(params[:id])
    if @signup.player_id != current_user.player.id && !current_user.admin && current_user.player.id != @signup.game.player.id
      flash[:notice] = "Not allowed to modify others' signups"
      redirect_to root_url
    end
  end
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/signups/_form.html.erb
<%= form_for(@signup) do |f| %>
  <% if @signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% @signup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br />
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :nation_id %><br />
    <%= f.number_field :nation_id %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br />
    <%= f.text_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing signup</h1>

<%= render 'form' %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<h1>Listing signups</h1>

<table>
  <tr>
    <th>Game</th>
    <th>Nation</th>
    <th>Password</th>
    <th>Status</th>
    <th>Player</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @signups.each do |signup| %>
  <tr>
    <td><%= signup.game_id %></td>
    <td><%= signup.nation_id %></td>
    <td><%= signup.password %></td>
    <td><%= signup.status %></td>
    <td><%= signup.player_id %></td>
    <td><%= link_to 'Show', signup %></td>
    <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
    <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Signup', new_signup_path %>

app/views/signups/new.html.erb
<h1>New signup</h1>

<%= render 'form' %>

<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @signup.game_id %>
</p>

<p>
  <b>Nation:</b>
  <%= @signup.nation_id %>
</p>

<p>
  <b>Password:</b>
  <%= @signup.password %>
</p>

<p>
  <b>Status:</b>
  <%= @signup.status %>
</p>

<p>
  <b>Player:</b>
  <%= @signup.player_id %>
</p>


<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>