config/routes.rb
Dom3::Application.routes.draw do
  resources :players do
    member do
      put 'updateAdmin'
    end
  end

  resources :signups

  resources :games

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "createuser" => "users#new", :as => "createuser"
  resources :users do
    member do
      get :activate
    end
  end
  resources :sessions
  resources :password_resets
  root :to => "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dominions 4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class = "maindiv">
      <% if current_user %>
        <p>Logged in as <%= current_user.username %>.</p>
        <%= link_to "Overview", root_url %>
        <%= link_to "Profile", :controller => "players", :action => "show", :id => current_user.player.id %>
        <%= link_to "Create Game", :controller => "games", :action => "new" %>
        <%= link_to "Edit Profile", :controller => "players", :action => "edit", :id => current_user.player.id %>
        <%= link_to "All Users", :controller => "players", :action => "index" %>
        <%= link_to "Log out", logout_path %>
      <% else %>
        <%= link_to "Sign up", createuser_path %> or
        <%= link_to "Log in", login_path %>.
      <% end %>
    </div>
    <br/>
<%= yield %>
</div>
</body>
</html>